CREATE TABLE admin_groupid
(
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 5000000 INCREMENT BY 1),
    public_id    TEXT UNIQUE  NOT NULL DEFAULT nanoid(),
    group_id     TEXT UNIQUE  NOT NULL,
    skip         BOOLEAN               DEFAULT FALSE,
    created      TIMESTAMP(3) NOT NULL DEFAULT NOW(),
    completed    TIMESTAMP(3),
    completed_by TEXT
);

ALTER TABLE company
  ADD COLUMN ad_group_id TEXT;
