CREATE TABLE task_summary
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 4000000 INCREMENT BY 1),
    task_id    BIGINT      NOT NULL,
    name       TEXT,
    raw        BYTEA,
    created    TIMESTAMP(3) NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_summary_task_task_id FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE CASCADE
);
