-- Summaries contain summarized data of tasks' or entry's results. The summaries may be generated at any point during
-- the entry processing.
CREATE TABLE summary
(
    id      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 6000000 INCREMENT BY 1),
    task_id BIGINT       NOT NULL,
    name    TEXT,
    raw     BYTEA,
    created TIMESTAMP(3) NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_summary_task_task_id FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE CASCADE
);
