-- Feature flags are simple boolean checks to allow enabling/disabling features of an app at will.
-- This table is temporal! public_id alone does not identify an unique row, instead you need to sort the results by
-- modified and pick the one that matches what you want, usually latest
CREATE TABLE feature_flag
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 7000000 INCREMENT BY 1),
    enabled     BOOLEAN               DEFAULT FALSE,
    name        TEXT         NOT NULL,
    modified    TIMESTAMP(3) NOT NULL DEFAULT NOW(),
    modified_by TEXT
);

CREATE INDEX idx_feature_flag_name ON feature_flag (name);
