-- Context is a user-controlled grouping of sources which can be used to determine which entries are related/distinct.
-- This forms the basis for sorting/ordering/limiting entry operations.
CREATE TABLE context
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 8000000 INCREMENT BY 1),
    context    TEXT   NOT NULL,
    company_id BIGINT NOT NULL,
    UNIQUE     (company_id, context),
    CONSTRAINT fk_context_company_company_id FOREIGN KEY (company_id) REFERENCES company (id)
);

-- entry optionally references the context, if present, to group entries together
ALTER TABLE entry
    ADD COLUMN context_id BIGINT,
    ADD CONSTRAINT fk_entry_context_context_id FOREIGN KEY (context_id) REFERENCES context (id) ON DELETE CASCADE;
