CREATE TABLE queue_entry
(
    id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    public_id TEXT DEFAULT nanoid(),
    "format"  TEXT NOT NULL,
    url       TEXT NOT NULL,
    etag      TEXT
);

CREATE TABLE queue_step
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1100000 INCREMENT BY 1),
    entry_id BIGINT       NOT NULL,
    phase    TEXT         NOT NULL,
    started  TIMESTAMP(3) NOT NULL,
    CONSTRAINT fk_step_entry_entry_id FOREIGN KEY (entry_id) REFERENCES queue_entry (id) ON DELETE CASCADE
);

CREATE TABLE queue_validation
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1200000 INCREMENT BY 1),
    entry_id BIGINT NOT NULL,
    CONSTRAINT fk_validation_entry_entry_id FOREIGN KEY (entry_id) REFERENCES queue_entry (id) ON DELETE CASCADE
);

CREATE TABLE queue_conversion
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1300000 INCREMENT BY 1),
    entry_id BIGINT NOT NULL,
    CONSTRAINT fk_conversion_entry_entry_id FOREIGN KEY (entry_id) REFERENCES queue_entry (id) ON DELETE CASCADE
);

CREATE TABLE queue_resource
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1400000 INCREMENT BY 1),
    entry_id BIGINT NOT NULL,
    path     TEXT   NOT NULL,
    CONSTRAINT fk_resource_entry_entry_id FOREIGN KEY (entry_id) REFERENCES queue_entry (id) ON DELETE CASCADE
);


