CREATE TABLE entry
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    public_id   TEXT UNIQUE NOT NULL DEFAULT nanoid(),
    "format"    TEXT        NOT NULL,
    url         TEXT        NOT NULL,
    business_id TEXT        NOT NULL,
    etag        TEXT,
    metadata    JSONB,
    created     TIMESTAMP(3) NOT NULL DEFAULT NOW(),
    started     TIMESTAMP(3),
    updated     TIMESTAMP(3),
    completed   TIMESTAMP(3)
);

CREATE TABLE phase
(
    id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1100000 INCREMENT BY 1),
    entry_id  BIGINT       NOT NULL,
    "name"    TEXT         NOT NULL,
    priority  INT          NOT NULL,
    started   TIMESTAMP(3) NOT NULL DEFAULT NOW(),
    updated   TIMESTAMP(3),
    completed TIMESTAMP(3),
    CONSTRAINT fk_phase_entry_entry_id FOREIGN KEY (entry_id) REFERENCES entry (id) ON DELETE CASCADE,
    UNIQUE (entry_id, name)
);

CREATE INDEX idx_phase_name ON phase
(
    name
);

CREATE TABLE validation_input
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1200000 INCREMENT BY 1),
    entry_id BIGINT NOT NULL,
    CONSTRAINT fk_validation_input_entry_entry_id FOREIGN KEY (entry_id) REFERENCES entry (id) ON DELETE CASCADE
);

CREATE TABLE conversion_input
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1300000 INCREMENT BY 1),
    entry_id BIGINT NOT NULL,
    target_format TEXT NOT NULL,
    CONSTRAINT fk_conversion_input_entry_entry_id FOREIGN KEY (entry_id) REFERENCES entry (id) ON DELETE CASCADE
);

CREATE TABLE generated_file
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1400000 INCREMENT BY 1),
    entry_id BIGINT NOT NULL,
    path     TEXT   NOT NULL,
    CONSTRAINT fk_generated_file_entry_entry_id FOREIGN KEY (entry_id) REFERENCES entry (id) ON DELETE CASCADE
);


