-- # Subscriptions
--
-- Subscription type describes a subscribable resource category
CREATE TYPE subscription_type AS ENUM ('webhook');

-- Dedicated table for tracking (WebHook) subscriptions between companies.
CREATE TABLE subscription
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 9000000 INCREMENT BY 1),
    public_id     TEXT UNIQUE NOT NULL DEFAULT nanoid(),
    type          subscription_type NOT NULL,
    subscriber_id BIGINT      NOT NULL,
    resource_id   BIGINT      NOT NULL,
    UNIQUE (type, subscriber_id, resource_id),
    CONSTRAINT fk_subscription_company_subscriber_id FOREIGN KEY (subscriber_id) REFERENCES company (id),
    CONSTRAINT fk_subscription_company_resource_id FOREIGN KEY (resource_id) REFERENCES company (id)
);
