CREATE TABLE feed
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    public_id TEXT UNIQUE NOT NULL DEFAULT nanoid(),
    owner TEXT NOT NULL,
    format TEXT NOT NULL,
    processing_enabled BOOLEAN,
    uri TEXT NOT NULL,
    query_params JSONB,
    http_method TEXT,
    request_body TEXT

);
