CREATE TABLE feed
(
    id                 BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1100000 INCREMENT BY 1),
    public_id          TEXT UNIQUE NOT NULL DEFAULT nanoid(),
    owner_id           BIGINT      NOT NULL,
    format             TEXT        NOT NULL,
    processing_enabled BOOLEAN     NOT NULL DEFAULT FALSE,
    uri                TEXT        NOT NULL,
    query_params       JSONB,
    http_method        TEXT,
    request_body       TEXT,
    CONSTRAINT fk_feed_company_owner_id FOREIGN KEY (owner_id) REFERENCES company (id)
);
