-- # Credentials storage for feeds
--
-- Credentials are admin configurable authentication details for allowing VACO to call protected APIs.

CREATE TYPE credentials_type AS ENUM ('HTTP Basic');

-- The table name is in plural due to commonality of using "credentials" instead of "credential". Convention beats
-- pedantry.
CREATE TABLE credentials
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1200000 INCREMENT BY 1),
    public_id   TEXT UNIQUE      NOT NULL DEFAULT nanoid(),
    owner_id    BIGINT           NOT NULL,
    name        TEXT             NOT NULL,
    type        credentials_type NOT NULL,
    description TEXT,
    details     BYTEA,
    UNIQUE (name, owner_id),
    CONSTRAINT fk_credentials_company_owner_id FOREIGN KEY (owner_id) REFERENCES company (id)
);

-- link entry to credentials
ALTER TABLE entry
  ADD COLUMN credentials_id BIGINT,
  ADD CONSTRAINT fk_entry_credentials_credentials_id FOREIGN KEY (credentials_id) REFERENCES credentials (id);
