CREATE TABLE tis_organization
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 3000000 INCREMENT BY 1),
    public_id   TEXT UNIQUE NOT NULL DEFAULT nanoid(),
    business_id TEXT        NOT NULL,
    name        TEXT
);

CREATE TYPE tis_cooperation_type AS ENUM ('authority-provider');

CREATE TABLE tis_cooperation
(
    type         tis_cooperation_type DEFAULT 'authority-provider',
    partner_b_id BIGINT NOT NULL,
    partner_b_id BIGINT NOT NULL,
    UNIQUE (type, partner_b_id, partner_b_id),
    CONSTRAINT fk_tis_collaboration_partner_b_id FOREIGN KEY (partner_b_id) REFERENCES tis_organization (id) ON DELETE CASCADE,
    CONSTRAINT fk_tis_collaboration_partner_b_id FOREIGN KEY (partner_b_id) REFERENCES tis_organization (id) ON DELETE CASCADE
);

CREATE TYPE validation_ruleset_category AS ENUM ('generic', 'specific');

CREATE TABLE validation_ruleset
(
    id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 2000000 INCREMENT BY 1),
    public_id        TEXT UNIQUE                 NOT NULL DEFAULT nanoid(),
    owner_id         BIGINT                      NOT NULL,
    category         validation_ruleset_category NOT NULL,
    identifying_name TEXT UNIQUE                 NOT NULL,
    description      TEXT                        NOT NULL,
    CONSTRAINT fk_validation_ruleset_owner_id FOREIGN KEY (owner_id) REFERENCES tis_organization (id) ON DELETE CASCADE
);

INSERT INTO tis_organization (business_id, name) VALUES ('2942108-7', 'Fintraffic Oy');
