CREATE TABLE organization
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 3000000 INCREMENT BY 1),
    public_id   TEXT UNIQUE NOT NULL DEFAULT nanoid(),
    business_id TEXT UNIQUE NOT NULL,
    name        TEXT
);

CREATE TYPE cooperation_type AS ENUM ('authority-provider');

CREATE TABLE cooperation
(
    type         cooperation_type DEFAULT 'authority-provider',
    partner_a_id BIGINT NOT NULL,
    partner_b_id BIGINT NOT NULL,
    UNIQUE (type, partner_a_id, partner_b_id),
    CONSTRAINT fk_collaboration_partner_a_id FOREIGN KEY (partner_a_id) REFERENCES organization (id) ON DELETE CASCADE,
    CONSTRAINT fk_collaboration_partner_b_id FOREIGN KEY (partner_b_id) REFERENCES organization (id) ON DELETE CASCADE
);

CREATE TYPE ruleset_category AS ENUM ('generic', 'specific');

CREATE TABLE ruleset
(
    id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 2000000 INCREMENT BY 1),
    public_id        TEXT UNIQUE                 NOT NULL DEFAULT nanoid(),
    owner_id         BIGINT                      NOT NULL,
    category         ruleset_category            NOT NULL,
    identifying_name TEXT UNIQUE                 NOT NULL,
    description      TEXT                        NOT NULL,
    "type"           TEXT                        NOT NULL,
    CONSTRAINT fk_ruleset_owner_id FOREIGN KEY (owner_id) REFERENCES organization (id) ON DELETE CASCADE
);
CREATE INDEX idx_ruleset_identifying_name ON ruleset
(
    identifying_name
);
