CREATE TABLE error_message
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 4000000 INCREMENT BY 1),
    public_id  TEXT UNIQUE NOT NULL DEFAULT nanoid(),
    entry_id   BIGINT      NOT NULL,
    phase_id   BIGINT      NOT NULL,
    ruleset_id BIGINT      NOT NULL,
    "message"  TEXT,
    raw        BYTEA,
    CONSTRAINT fk_error_message_queue_entry_entry_id FOREIGN KEY (entry_id) REFERENCES queue_entry (id) ON DELETE CASCADE,
    CONSTRAINT fk_error_message_queue_phase_phase_id FOREIGN KEY (phase_id) REFERENCES queue_phase (id) ON DELETE CASCADE,
    CONSTRAINT fk_error_message_validation_ruleset_validation_ruleset_id FOREIGN KEY (ruleset_id) REFERENCES validation_ruleset (id) ON DELETE CASCADE
);
