CREATE TABLE error
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 4000000 INCREMENT BY 1),
    public_id  TEXT UNIQUE NOT NULL DEFAULT nanoid(),
    entry_id   BIGINT      NOT NULL,
    phase_id   BIGINT      NOT NULL,
    ruleset_id BIGINT      NOT NULL,
    "message"  TEXT,
    raw        BYTEA,
    CONSTRAINT fk_error_message_entry_entry_id FOREIGN KEY (entry_id) REFERENCES entry (id) ON DELETE CASCADE,
    CONSTRAINT fk_error_message_phase_phase_id FOREIGN KEY (phase_id) REFERENCES phase (id) ON DELETE CASCADE,
    CONSTRAINT fk_error_message_ruleset_id FOREIGN KEY (ruleset_id) REFERENCES ruleset (id) ON DELETE CASCADE
);
