version: 2
updates:
  # keep used GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "tmfg/digitraffic-tis-solita"
    groups:
      actions-deps:
        patterns:
          - "*"
