version: 2
updates:
  # keep used GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 2
    groups:
      actions-deps:
        patterns:
          - "*"
